capture_interval = '2s'
check_interval = '10s'

web = '127.0.0.1:8080'

username = 'admin'
password = 'admin'

[[tic]]
type = 'local'
blacklist = ['1.1.1.1']

# [[tic]]
# type = 'threatbook'
# apikey = 'xxx'
